/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRewardsDistributor,
  IRewardsDistributorInterface,
} from "../../../contracts/interfaces/IRewardsDistributor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "claim",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "usdSupplied",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "usdBorrowed",
        type: "uint256",
      },
    ],
    name: "onAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "perSec",
        type: "uint256",
      },
    ],
    name: "setEmissionPerSec",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRewardsDistributor__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardsDistributorInterface {
    return new Interface(_abi) as IRewardsDistributorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRewardsDistributor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRewardsDistributor;
  }
}
