/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ILoanManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "getLoanToken" | "getOutstandingLoanUSD" | "repayFor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLoanToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingLoanUSD",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repayFor",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLoanToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingLoanUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayFor", data: BytesLike): Result;
}

export interface ILoanManager extends BaseContract {
  connect(runner?: ContractRunner | null): ILoanManager;
  waitForDeployment(): Promise<this>;

  interface: ILoanManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLoanToken: TypedContractMethod<[user: AddressLike], [string], "view">;

  getOutstandingLoanUSD: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  repayFor: TypedContractMethod<
    [borrower: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLoanToken"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getOutstandingLoanUSD"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "repayFor"
  ): TypedContractMethod<
    [borrower: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
