/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CollateralManager } from "./CollateralManager";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { ILoanManager } from "./ILoanManager";
export type { IPriceOracle } from "./IPriceOracle";
