/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICollateralManager } from "./ICollateralManager";
export type { IPriceOracle } from "./IPriceOracle";
export type { LoanManager } from "./LoanManager";
