/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LoanManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeBorrowers"
      | "calculateInterest"
      | "calculateLenderReward"
      | "claimRewards"
      | "collateralManager"
      | "depositToPool"
      | "getActiveBorrowerCount"
      | "getActiveBorrowers"
      | "getAvailableLiquidity"
      | "getLoanToken"
      | "getOutstandingLoan"
      | "getOutstandingLoanUSD"
      | "isBorrower"
      | "isSupportedToken"
      | "lenders"
      | "loans"
      | "owner"
      | "priceOracle"
      | "protocolProfit"
      | "ratesByToken"
      | "renounceOwnership"
      | "repay"
      | "repayAll"
      | "repayFor"
      | "requestLoan"
      | "rewardToken"
      | "rewardsDistributor"
      | "setPriceOracle"
      | "setRewardToken"
      | "setRewardsDistributor"
      | "supportToken"
      | "transferOwnership"
      | "treasury"
      | "withdraw"
      | "withdrawAll"
      | "withdrawProtocolProfit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositedToPool"
      | "LoanRepaid"
      | "LoanRepaidFor"
      | "LoanRequested"
      | "OwnershipTransferred"
      | "RewardDistributed"
      | "RewardsDistributorUpdated"
      | "TokenSupported"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeBorrowers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateInterest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateLenderReward",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToPool",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveBorrowerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveBorrowers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableLiquidity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingLoan",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingLoanUSD",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBorrower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lenders",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolProfit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ratesByToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayAll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repayFor",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardsDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardsDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportToken",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProtocolProfit",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeBorrowers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateLenderReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveBorrowerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveBorrowers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingLoanUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBorrower", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lenders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratesByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repayAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repayFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardsDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardsDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProtocolProfit",
    data: BytesLike
  ): Result;
}

export namespace DepositedToPoolEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    repayAmount: BigNumberish,
    remainingDebt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    repayAmount: bigint,
    remainingDebt: bigint
  ];
  export interface OutputObject {
    user: string;
    token: string;
    repayAmount: bigint;
    remainingDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidForEvent {
  export type InputTuple = [
    payer: AddressLike,
    borrower: AddressLike,
    token: AddressLike,
    paid: BigNumberish
  ];
  export type OutputTuple = [
    payer: string,
    borrower: string,
    token: string,
    paid: bigint
  ];
  export interface OutputObject {
    payer: string;
    borrower: string;
    token: string;
    paid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRequestedEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    principal: BigNumberish,
    rateBps: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    principal: bigint,
    rateBps: bigint
  ];
  export interface OutputObject {
    user: string;
    token: string;
    principal: bigint;
    rateBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributorUpdatedEvent {
  export type InputTuple = [distributor: AddressLike];
  export type OutputTuple = [distributor: string];
  export interface OutputObject {
    distributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSupportedEvent {
  export type InputTuple = [
    token: AddressLike,
    borrowRateBps: BigNumberish,
    lendRateBps: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    borrowRateBps: bigint,
    lendRateBps: bigint
  ];
  export interface OutputObject {
    token: string;
    borrowRateBps: bigint;
    lendRateBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    principalOut: BigNumberish,
    interestOut: BigNumberish,
    totalOut: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    principalOut: bigint,
    interestOut: bigint,
    totalOut: bigint
  ];
  export interface OutputObject {
    user: string;
    token: string;
    principalOut: bigint;
    interestOut: bigint;
    totalOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoanManager extends BaseContract {
  connect(runner?: ContractRunner | null): LoanManager;
  waitForDeployment(): Promise<this>;

  interface: LoanManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeBorrowers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  calculateInterest: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  calculateLenderReward: TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  collateralManager: TypedContractMethod<[], [string], "view">;

  depositToPool: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveBorrowerCount: TypedContractMethod<[], [bigint], "view">;

  getActiveBorrowers: TypedContractMethod<[], [string[]], "view">;

  getAvailableLiquidity: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  getLoanToken: TypedContractMethod<[user: AddressLike], [string], "view">;

  getOutstandingLoan: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getOutstandingLoanUSD: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  isBorrower: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isSupportedToken: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lenders: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        deposited: bigint;
        depositTime: bigint;
        rewardClaimed: bigint;
      }
    ],
    "view"
  >;

  loans: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        token: string;
        principal: bigint;
        rate: bigint;
        totalInterest: bigint;
        createdAt: bigint;
        duration: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  protocolProfit: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  ratesByToken: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { borrowRate: bigint; lendRate: bigint }],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repay: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  repayAll: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  repayFor: TypedContractMethod<
    [borrower: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestLoan: TypedContractMethod<
    [token: AddressLike, principal: BigNumberish, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  rewardToken: TypedContractMethod<[], [string], "view">;

  rewardsDistributor: TypedContractMethod<[], [string], "view">;

  setPriceOracle: TypedContractMethod<
    [_oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setRewardToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  setRewardsDistributor: TypedContractMethod<
    [distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  supportToken: TypedContractMethod<
    [
      token: AddressLike,
      borrowRateBps: BigNumberish,
      lendRateBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalDeposits: bigint;
        totalBorrows: bigint;
        totalRepayments: bigint;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawAll: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  withdrawProtocolProfit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeBorrowers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "calculateInterest"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateLenderReward"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositToPool"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveBorrowerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveBorrowers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAvailableLiquidity"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLoanToken"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getOutstandingLoan"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOutstandingLoanUSD"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isBorrower"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSupportedToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lenders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        deposited: bigint;
        depositTime: bigint;
        rewardClaimed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        token: string;
        principal: bigint;
        rate: bigint;
        totalInterest: bigint;
        createdAt: bigint;
        duration: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolProfit"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "ratesByToken"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { borrowRate: bigint; lendRate: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayAll"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayFor"
  ): TypedContractMethod<
    [borrower: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<
    [token: AddressLike, principal: BigNumberish, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardsDistributor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPriceOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardsDistributor"
  ): TypedContractMethod<[distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      borrowRateBps: BigNumberish,
      lendRateBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalDeposits: bigint;
        totalBorrows: bigint;
        totalRepayments: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawAll"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawProtocolProfit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DepositedToPool"
  ): TypedContractEvent<
    DepositedToPoolEvent.InputTuple,
    DepositedToPoolEvent.OutputTuple,
    DepositedToPoolEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaidFor"
  ): TypedContractEvent<
    LoanRepaidForEvent.InputTuple,
    LoanRepaidForEvent.OutputTuple,
    LoanRepaidForEvent.OutputObject
  >;
  getEvent(
    key: "LoanRequested"
  ): TypedContractEvent<
    LoanRequestedEvent.InputTuple,
    LoanRequestedEvent.OutputTuple,
    LoanRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributorUpdated"
  ): TypedContractEvent<
    RewardsDistributorUpdatedEvent.InputTuple,
    RewardsDistributorUpdatedEvent.OutputTuple,
    RewardsDistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenSupported"
  ): TypedContractEvent<
    TokenSupportedEvent.InputTuple,
    TokenSupportedEvent.OutputTuple,
    TokenSupportedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "DepositedToPool(address,address,uint256)": TypedContractEvent<
      DepositedToPoolEvent.InputTuple,
      DepositedToPoolEvent.OutputTuple,
      DepositedToPoolEvent.OutputObject
    >;
    DepositedToPool: TypedContractEvent<
      DepositedToPoolEvent.InputTuple,
      DepositedToPoolEvent.OutputTuple,
      DepositedToPoolEvent.OutputObject
    >;

    "LoanRepaid(address,address,uint256,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanRepaidFor(address,address,address,uint256)": TypedContractEvent<
      LoanRepaidForEvent.InputTuple,
      LoanRepaidForEvent.OutputTuple,
      LoanRepaidForEvent.OutputObject
    >;
    LoanRepaidFor: TypedContractEvent<
      LoanRepaidForEvent.InputTuple,
      LoanRepaidForEvent.OutputTuple,
      LoanRepaidForEvent.OutputObject
    >;

    "LoanRequested(address,address,uint256,uint256)": TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
    LoanRequested: TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardDistributed(address,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "RewardsDistributorUpdated(address)": TypedContractEvent<
      RewardsDistributorUpdatedEvent.InputTuple,
      RewardsDistributorUpdatedEvent.OutputTuple,
      RewardsDistributorUpdatedEvent.OutputObject
    >;
    RewardsDistributorUpdated: TypedContractEvent<
      RewardsDistributorUpdatedEvent.InputTuple,
      RewardsDistributorUpdatedEvent.OutputTuple,
      RewardsDistributorUpdatedEvent.OutputObject
    >;

    "TokenSupported(address,uint256,uint256)": TypedContractEvent<
      TokenSupportedEvent.InputTuple,
      TokenSupportedEvent.OutputTuple,
      TokenSupportedEvent.OutputObject
    >;
    TokenSupported: TypedContractEvent<
      TokenSupportedEvent.InputTuple,
      TokenSupportedEvent.OutputTuple,
      TokenSupportedEvent.OutputObject
    >;

    "Withdrawn(address,address,uint256,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
