/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as collateralManagerSol from "./CollateralManager.sol";
export type { collateralManagerSol };
import type * as loanManagerSol from "./LoanManager.sol";
export type { loanManagerSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ManualPriceOracle } from "./ManualPriceOracle";
export type { NYRAToken } from "./NYRAToken";
export type { RewardsDistributor } from "./RewardsDistributor";
export type { TestToken } from "./TestToken";
