/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RewardsDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accRewardPerPoint"
      | "borrowWeightBps"
      | "claim(address)"
      | "claim(address,address)"
      | "claimForSelf"
      | "emissionPerSec"
      | "fund"
      | "lastUpdate"
      | "onAction"
      | "owner"
      | "pendingRewards"
      | "pointsManager"
      | "renounceOwnership"
      | "rewardToken"
      | "setBorrowWeightBps"
      | "setEmissionPerSec"
      | "setPointsManager"
      | "totalPoints"
      | "transferOwnership"
      | "users"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BorrowWeightUpdated"
      | "EmissionUpdated"
      | "Funded"
      | "OwnershipTransferred"
      | "PointsManagerUpdated"
      | "PointsUpdated"
      | "RewardsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accRewardPerPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowWeightBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claim(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimForSelf",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emissionPerSec",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "lastUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onAction",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pointsManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBorrowWeightBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmissionPerSec",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPointsManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;

  decodeFunctionResult(
    functionFragment: "accRewardPerPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowWeightBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claim(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claim(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimForSelf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emissionPerSec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastUpdate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onAction", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pointsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBorrowWeightBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmissionPerSec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPointsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
}

export namespace BorrowWeightUpdatedEvent {
  export type InputTuple = [newBorrowWeightBps: BigNumberish];
  export type OutputTuple = [newBorrowWeightBps: bigint];
  export interface OutputObject {
    newBorrowWeightBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmissionUpdatedEvent {
  export type InputTuple = [newEmissionPerSec: BigNumberish];
  export type OutputTuple = [newEmissionPerSec: bigint];
  export interface OutputObject {
    newEmissionPerSec: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsManagerUpdatedEvent {
  export type InputTuple = [newManager: AddressLike];
  export type OutputTuple = [newManager: string];
  export interface OutputObject {
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsUpdatedEvent {
  export type InputTuple = [user: AddressLike, newPoints: BigNumberish];
  export type OutputTuple = [user: string, newPoints: bigint];
  export interface OutputObject {
    user: string;
    newPoints: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardsDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): RewardsDistributor;
  waitForDeployment(): Promise<this>;

  interface: RewardsDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accRewardPerPoint: TypedContractMethod<[], [bigint], "view">;

  borrowWeightBps: TypedContractMethod<[], [bigint], "view">;

  "claim(address)": TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  "claim(address,address)": TypedContractMethod<
    [user: AddressLike, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  claimForSelf: TypedContractMethod<[], [bigint], "nonpayable">;

  emissionPerSec: TypedContractMethod<[], [bigint], "view">;

  fund: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  lastUpdate: TypedContractMethod<[], [bigint], "view">;

  onAction: TypedContractMethod<
    [user: AddressLike, usdSupplied: BigNumberish, usdBorrowed: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingRewards: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  pointsManager: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardToken: TypedContractMethod<[], [string], "view">;

  setBorrowWeightBps: TypedContractMethod<
    [newWeightBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setEmissionPerSec: TypedContractMethod<
    [perSec: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPointsManager: TypedContractMethod<
    [manager: AddressLike],
    [void],
    "nonpayable"
  >;

  totalPoints: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        points: bigint;
        rewardDebt: bigint;
        pending: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accRewardPerPoint"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "borrowWeightBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claim(address)"
  ): TypedContractMethod<[user: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claim(address,address)"
  ): TypedContractMethod<
    [user: AddressLike, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimForSelf"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "emissionPerSec"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lastUpdate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onAction"
  ): TypedContractMethod<
    [user: AddressLike, usdSupplied: BigNumberish, usdBorrowed: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingRewards"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pointsManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBorrowWeightBps"
  ): TypedContractMethod<[newWeightBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEmissionPerSec"
  ): TypedContractMethod<[perSec: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPointsManager"
  ): TypedContractMethod<[manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        points: bigint;
        rewardDebt: bigint;
        pending: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BorrowWeightUpdated"
  ): TypedContractEvent<
    BorrowWeightUpdatedEvent.InputTuple,
    BorrowWeightUpdatedEvent.OutputTuple,
    BorrowWeightUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmissionUpdated"
  ): TypedContractEvent<
    EmissionUpdatedEvent.InputTuple,
    EmissionUpdatedEvent.OutputTuple,
    EmissionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PointsManagerUpdated"
  ): TypedContractEvent<
    PointsManagerUpdatedEvent.InputTuple,
    PointsManagerUpdatedEvent.OutputTuple,
    PointsManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PointsUpdated"
  ): TypedContractEvent<
    PointsUpdatedEvent.InputTuple,
    PointsUpdatedEvent.OutputTuple,
    PointsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;

  filters: {
    "BorrowWeightUpdated(uint256)": TypedContractEvent<
      BorrowWeightUpdatedEvent.InputTuple,
      BorrowWeightUpdatedEvent.OutputTuple,
      BorrowWeightUpdatedEvent.OutputObject
    >;
    BorrowWeightUpdated: TypedContractEvent<
      BorrowWeightUpdatedEvent.InputTuple,
      BorrowWeightUpdatedEvent.OutputTuple,
      BorrowWeightUpdatedEvent.OutputObject
    >;

    "EmissionUpdated(uint256)": TypedContractEvent<
      EmissionUpdatedEvent.InputTuple,
      EmissionUpdatedEvent.OutputTuple,
      EmissionUpdatedEvent.OutputObject
    >;
    EmissionUpdated: TypedContractEvent<
      EmissionUpdatedEvent.InputTuple,
      EmissionUpdatedEvent.OutputTuple,
      EmissionUpdatedEvent.OutputObject
    >;

    "Funded(address,uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PointsManagerUpdated(address)": TypedContractEvent<
      PointsManagerUpdatedEvent.InputTuple,
      PointsManagerUpdatedEvent.OutputTuple,
      PointsManagerUpdatedEvent.OutputObject
    >;
    PointsManagerUpdated: TypedContractEvent<
      PointsManagerUpdatedEvent.InputTuple,
      PointsManagerUpdatedEvent.OutputTuple,
      PointsManagerUpdatedEvent.OutputObject
    >;

    "PointsUpdated(address,uint256)": TypedContractEvent<
      PointsUpdatedEvent.InputTuple,
      PointsUpdatedEvent.OutputTuple,
      PointsUpdatedEvent.OutputObject
    >;
    PointsUpdated: TypedContractEvent<
      PointsUpdatedEvent.InputTuple,
      PointsUpdatedEvent.OutputTuple,
      PointsUpdatedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
  };
}
