/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICollateralManager,
  ICollateralManagerInterface,
} from "../../../contracts/LoanManager.sol/ICollateralManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getCollateralValueUSD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getHealthFactor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICollateralManager__factory {
  static readonly abi = _abi;
  static createInterface(): ICollateralManagerInterface {
    return new Interface(_abi) as ICollateralManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICollateralManager {
    return new Contract(address, _abi, runner) as unknown as ICollateralManager;
  }
}
