import fs from "fs";
import path from "path";

const NETWORKS = [{ name: "arc", chainId: 5042002 }];
const NAME_MAP = { NYRAToken: "NYRA" };
const STATIC_CONTRACTS = ["USDC", "EURC"];
const line = "\n===================================================================\n";

const contractsDir = path.resolve("../contracts");
const deploymentsDir = path.join(contractsDir, "deployments", "arc");
const outDir = path.resolve("./src/abi");

if (!fs.existsSync(contractsDir)) {
  console.error(`${line}Unable to locate ../contracts (run inside /frontend).${line}`);
  process.exit(1);
}
if (!fs.existsSync(deploymentsDir)) {
  console.error(`${line}No deployments found for 'arc'. Run 'npx hardhat deploy --network arc'.${line}`);
  process.exit(1);
}
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

function loadContracts() {
  const files = fs.readdirSync(deploymentsDir).filter((f) => f.endsWith(".json"));
  return files.map((file) => {
    const rawName = path.basename(file, ".json");
    const mappedName = NAME_MAP[rawName] ?? rawName;
    return { name: mappedName, sourceName: rawName };
  });
}

function readDeployment(chain, contract) {
  const filePath = path.join(deploymentsDir, `${contract}.json`);
  if (!fs.existsSync(filePath)) {
    console.error(
      `${line}Missing deployment for ${contract} on '${chain.name}'.\n` +
        `1. cd ../contracts\n2. npx hardhat deploy --network ${chain.name}${line}`,
    );
    process.exit(1);
  }
  const json = JSON.parse(fs.readFileSync(filePath, "utf-8"));
  return { abi: json.abi, address: json.address, chainId: chain.chainId, chainName: chain.name };
}

function writeAbiFiles(name, deployments) {
  const abiSource = deployments[0].abi;
  const abiCode = `/*
  Auto-generated by 'npm run genabi'
*/
export const ${name}ABI = ${JSON.stringify({ abi: abiSource }, null, 2)} as const;
`;

  const addressEntries = deployments
    .map(
      (d) =>
        `  "${d.chainId}": { address: "${d.address}", chainId: ${d.chainId}, chainName: "${d.chainName}" },`,
    )
    .join("\n");

  const addrCode = `/*
  Auto-generated by 'npm run genabi'
*/
export const ${name}Addresses = {
${addressEntries}
} as const;
`;

  fs.writeFileSync(path.join(outDir, `${name}ABI.ts`), abiCode);
  fs.writeFileSync(path.join(outDir, `${name}Addresses.ts`), addrCode);
}

const generated = [];

loadContracts().forEach(({ name, sourceName }) => {
  console.log(`\n🔄 Generating ${name}...`);
  const deployments = NETWORKS.map((net) => readDeployment(net, sourceName));
  writeAbiFiles(name, deployments);
  generated.push(name);
  console.log(`✅ Generated ${name}ABI.ts & ${name}Addresses.ts`);
});

STATIC_CONTRACTS.forEach((name) => {
  const abiPath = path.join(outDir, `${name}ABI.ts`);
  const addrPath = path.join(outDir, `${name}Addresses.ts`);
  if (fs.existsSync(abiPath) && fs.existsSync(addrPath) && !generated.includes(name)) {
    generated.push(name);
  }
});

const contractsFile = `/*
  Auto-generated by 'npm run genabi'
*/
${generated
  .map(
    (name) =>
      `import { ${name}ABI } from './${name}ABI';
import { ${name}Addresses } from './${name}Addresses';`,
  )
  .join("\n")}

export const ABIs = {
${generated.map((name) => `  ${name}: ${name}ABI.abi,`).join("\n")}
};

export const Addresses = {
${generated.map((name) => `  ${name}: ${name}Addresses,`).join("\n")}
};

${generated.map((name) => `export { ${name}ABI, ${name}Addresses };`).join("\n")}
`;

fs.writeFileSync(path.join(outDir, "contracts.ts"), contractsFile);

console.log(`\n🎉 Generated contracts:`);
generated.forEach((name) => {
  console.log(`   - ${name}ABI.ts`);
  console.log(`   - ${name}Addresses.ts`);
});
console.log(`   - contracts.ts\n`);
console.log(`📝 Usage: import { ABIs, Addresses } from '@/abi/contracts';`);

