/*
  Auto-generated by 'npm run genabi'
*/
export const CollateralManagerAddresses = {
  "5042002": { address: "0xe50f842f4B4E9d3ee5BF1c55F87B68B277Fb6bBc", chainId: 5042002, chainName: "arc" },
} as const;
