/*
  Auto-generated by 'npm run genabi'
*/
export const CollateralManagerAddresses = {
  "5042002": { address: "0x72E80853F6676e6Eb6dcc1527ccbAd82C36DeA55", chainId: 5042002, chainName: "arc" },
} as const;
