/*
  Auto-generated by 'npm run genabi'
*/
export const CollateralManagerAddresses = {
  "5042002": { address: "0x8AEA119412C71a7ad1c3fb6bab0A3cd6E93c4a76", chainId: 5042002, chainName: "arc" },
} as const;
