/*
  Auto-generated by 'npm run genabi'
*/
import { BNBABI } from './BNBABI';
import { BNBAddresses } from './BNBAddresses';
import { BTCABI } from './BTCABI';
import { BTCAddresses } from './BTCAddresses';
import { CollateralManagerABI } from './CollateralManagerABI';
import { CollateralManagerAddresses } from './CollateralManagerAddresses';
import { ETHABI } from './ETHABI';
import { ETHAddresses } from './ETHAddresses';
import { LoanManagerABI } from './LoanManagerABI';
import { LoanManagerAddresses } from './LoanManagerAddresses';
import { ManualPriceOracleABI } from './ManualPriceOracleABI';
import { ManualPriceOracleAddresses } from './ManualPriceOracleAddresses';
import { NYRAABI } from './NYRAABI';
import { NYRAAddresses } from './NYRAAddresses';
import { RewardsDistributorABI } from './RewardsDistributorABI';
import { RewardsDistributorAddresses } from './RewardsDistributorAddresses';
import { USDCABI } from './USDCABI';
import { USDCAddresses } from './USDCAddresses';
import { EURCABI } from './EURCABI';
import { EURCAddresses } from './EURCAddresses';

export const ABIs = {
  BNB: BNBABI.abi,
  BTC: BTCABI.abi,
  CollateralManager: CollateralManagerABI.abi,
  ETH: ETHABI.abi,
  LoanManager: LoanManagerABI.abi,
  ManualPriceOracle: ManualPriceOracleABI.abi,
  NYRA: NYRAABI.abi,
  RewardsDistributor: RewardsDistributorABI.abi,
  USDC: USDCABI.abi,
  EURC: EURCABI.abi,
};

export const Addresses = {
  BNB: BNBAddresses,
  BTC: BTCAddresses,
  CollateralManager: CollateralManagerAddresses,
  ETH: ETHAddresses,
  LoanManager: LoanManagerAddresses,
  ManualPriceOracle: ManualPriceOracleAddresses,
  NYRA: NYRAAddresses,
  RewardsDistributor: RewardsDistributorAddresses,
  USDC: USDCAddresses,
  EURC: EURCAddresses,
};

export { BNBABI, BNBAddresses };
export { BTCABI, BTCAddresses };
export { CollateralManagerABI, CollateralManagerAddresses };
export { ETHABI, ETHAddresses };
export { LoanManagerABI, LoanManagerAddresses };
export { ManualPriceOracleABI, ManualPriceOracleAddresses };
export { NYRAABI, NYRAAddresses };
export { RewardsDistributorABI, RewardsDistributorAddresses };
export { USDCABI, USDCAddresses };
export { EURCABI, EURCAddresses };
