/*
  Auto-generated by 'npm run genabi'
*/
export const LoanManagerAddresses = {
  "5042002": { address: "0x8232C0C19bF20641d4709c87315A4F72580c4fAb", chainId: 5042002, chainName: "arc" },
} as const;
