/*
  Auto-generated by 'npm run genabi'
*/
export const LoanManagerAddresses = {
  "5042002": { address: "0x3533EDD113C53178D66Ec927Bf7e48f9fC85F4b3", chainId: 5042002, chainName: "arc" },
} as const;
