/*
  Auto-generated by 'npm run genabi'
*/
export const LoanManagerAddresses = {
  "5042002": { address: "0x94B735e9EF9Be8774aF9583adD76f1bB308d6b81", chainId: 5042002, chainName: "arc" },
} as const;
