/*
  Auto-generated by 'npm run genabi'
*/
export const ManualPriceOracleAddresses = {
  "5042002": { address: "0x3af7cF2b0f3FDd02a7CD11722Ab026AB224DD245", chainId: 5042002, chainName: "arc" },
} as const;
