/*
  Auto-generated by 'npm run genabi'
*/
export const ManualPriceOracleAddresses = {
  "5042002": { address: "0xE047F8C424eD711f76171d7e8526Fa4c38645Efe", chainId: 5042002, chainName: "arc" },
} as const;
