/*
  Auto-generated by 'npm run genabi'
*/
export const ManualPriceOracleAddresses = {
  "5042002": { address: "0x5929785cb88C4dfdaaA54323841aE2a19a3A0D52", chainId: 5042002, chainName: "arc" },
} as const;
