/*
  Auto-generated by 'npm run genabi'
*/
export const RewardsDistributorAddresses = {
  "5042002": { address: "0x57b1Cf21636c9D312a28e277128C3521581C8758", chainId: 5042002, chainName: "arc" },
} as const;
